<a href="https://colab.research.google.com/github/TRANTHITHUYTIEN20104061/Tr-n-Th-Th-y-Ti-n-20104061/blob/main/Buoi4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
x=[0,0],[1,0],[0,1],[1,1]
y=[0,1,1,1]
model=Perceptron()
model.fit(x,y)
print('Do chinh xac', model.score(x,y))
x_test=[[0.5,0],[0.9,-0.2],[1,-0.5],[0.2,0.7]]
y_test=model.predict(x_test)
print(y_test)

Do chinh xac 1.0
[0 1 0 1]


In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
data=pd.read_csv('/crabs.csv')
x=data.drop(['speies','sex'],axis=1)
y = data['sex'].replace(['M','F'],[0,1])
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3)




SyntaxError: ignored

In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
import pandas as pd
url= '/crabs.csv'
data= pd.read_csv(url)
x = data.drop(['speies','sex'],axis = True)
y = data['sex'].replace(['M','F'],[0,1])
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3)

model = Perceptron()
model.fit(x_train,y_train)
print('do chinh xac',model.score(x_train,y_train))
x_t = [[42,15.6,14.7,33.9,39.5,14.3],[44,21.5,15.5,45.5,49.7,20.9],[45,21.3,18.4,43.8,48.4,20]]
y_pre = model.predict(x_t)
print(y_pre)

do chinh xac 0.9
[1 0 1]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
iris = load_iris()
for n, i in enumerate(iris.target):
  if i == 2:
    iris.target[n] = 1
for n, i in enumerate(iris.target):
  if i == 2:
    iris.target[n] = 1
x = iris.data
y = iris.target
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.5)
model = Perceptron()
model.fit(x_train,y_train)
print('đo chinh xac',model.score(x_test,y_test))
x_test = [[5,3,1,0.2],[5,3,4,1.3],[4,4,3,0.2]]
y_test = model.predict(x_test)
print(y_test)





đo chinh xac 0.9866666666666667
[0 1 0]
